### ISSUE TITLE
不同宽高视频的播放问题

### ISSUE THREAD

**Issue by luoyou592** [moyokoo/DragDiooto#1]
播放视频得提前获取他们的宽高吗？来设置dragDiootoView.notifySize(1920, 1080)，这个方法吗

**Comment by moyokoo** [comment]
这个是播放后 进行大小的更新

**Comment by luoyou592** [comment]
我现在用你的demo播放竖屏的视频，话面只显示中间部分，需要操作哪里才能智能播放不同宽高比例的视频呢

**Comment by luoyou592** [comment]
build-tools\26.0.2\aapt.exe'' finished with non-zero exit value 1
项目添加ui库就报这个错，有想法指点吗

**Comment by moyokoo** [comment]
UI库指的是什么库

**Comment by luoyou592** [comment]
artplayer-ui:0.6.0

**Comment by moyokoo** [comment]
播放器问题可以移步 [ArtPlayer](https://github.com/maiwenchang/ArtPlayer/issues)
